### PR TITLE
add memcached png

### PR DESCRIPTION
**Pull request by ascrutae**

### CODE REVIEW

**Comment by IluckySi** [comment]
3q! @ascrutae

**Comment by wu-sheng** [comment]
@ascrutae @IluckySi I will keep this open, until we are ready to merge the memcached plugin in sky-walking repo. OK?

**Comment by IluckySi** [comment]
OK! @ascrutae @wu-sheng

**Comment by wu-sheng** [comment]
@IluckySi Byte-buddy 1.7.6 has released, resolved exception issue. https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.7.6

I think you can work on memcached plugin, after you send a pr to update byte-buddy to 1.7.6

**Comment by IluckySi** [comment]
OK！

**Pull request merged**
