### PR TITLE
Topology graph demo

### PR DESCRIPTION
**Pull request by hanahmily**
There is a `topology-graph-demo` folder in the branch. Please accessing `app.html` to view the demo. 

Every one in @OpenSkywalking/pmc  cloud reply this pr to give advise.

### CODE REVIEW

**Comment by hanahmily** [comment]
You can the answer of the 1, 3 and 4 questions in  this [commit](https://github.com/OpenSkywalking/skywalking-ui/pull/82/commits/dc802486cb48464daf9ee614fcfb2b2a94c4bf96).

For the 2 question, the answer is yes, but it does not make any sense. You can't reach the link in a circle that is the result of render of canvas.
Alternatively I will add click event to the node, the result of event is showing alarm in another html panel.The above approach to meet the needs ？

**Comment by wu-sheng** [comment]
> For the 2 question, the answer is yes, but it does not make any sense. You can't reach the link in a circle that is the result of render of canvas.
Alternatively I will add click event to the node, the result of event is showing alarm in another html panel.The above approach to meet the needs ？

I intend to be sure about the tech stack capabilities, not just we are going to do. So, don't bother the use cases.

**Comment by wu-sheng** [comment]
@hanahmily I can see that, you implement the cycle click event, and trigger the link invalid. In real implementation level,

I am sure we are going to use links instead of the single cycle click event.

But I have to say, the default size of the cycle and alerting links is too small. It is hard to click,  unless zoom in.

**Comment by wu-sheng** [comment]
Sorry, @hanahmily . I miss an important thing for the topology. For every application, there should be multi alerting info for single application. So we should remove the first altering icon and number next to it. If the application alarm happens, the application cycle turns to **red**.

Hope you can make sure, this will work in the demonstration.

**Pull request closed without merging**
