### PR TITLE
bugFix:wrong js reference

### PR DESCRIPTION
**Pull request by zuohl**

### CODE REVIEW

**Comment by peng-yongsheng** [comment]
@zuohl 
This is webjar maven dependency, the version of moment.js seems good.
wechatimg10633

**Comment by zuohl** [comment]
@peng-yongsheng may be your local jar is cached,the momentjs is dependency from bootstrap-daterangepicker 2.1.24,

below is the content of  bootstrap-daterangepicker-2.1.24.pom

**Comment by zuohl** [comment]
@peng-yongsheng  or you can download skywalking-web.tar.gz from https://github.com/OpenSkywalking/skywalking/releases and then you can see the libs

**Comment by peng-yongsheng** [comment]
@zuohl So, suggest add the dependency of moment.js webjars into pom, but not change the version of moment.js in htmls.

**Comment by zuohl** [comment]
@peng-yongsheng ok

**Comment by peng-yongsheng** [comment]
@zuohl Don't forget exclude the moment.js dependency in daterangepicker.

**Comment by zuohl** [comment]
@peng-yongsheng of course

**Comment by wu-sheng** [comment]
@zuohl since you are a contributor of this project, please pay attention on this: https://github.com/OpenSkywalking/Organization/pull/1 . Send your pr into `contrib-list` branch with your info.

**Comment by wu-sheng** [comment]
@zuohl 有急事找你帮忙，请回复邮件到wu.sheng@foxmail.com

**Pull request merged**
