### PR TITLE
Add memcache icon

### PR DESCRIPTION
**Pull request by IluckySi**
Add memcache icon #https://github.com/OpenSkywalking/skywalking/pull/518

### CODE REVIEW

**Comment by wu-sheng** [comment]
what is the difference between this and #72?

**Comment by IluckySi** [comment]
I forget the #72 , the name is different! MEMCACH.png not MEMCACHED.png

**Comment by IluckySi** [comment]
#72 can be closed!

**Comment by wu-sheng** [comment]
First, I fixed an issue about your prev pull request. The component name is `MEMCACHED` instead of `MEMCACHE`. So I think #75 is right.

**Pull request closed without merging**
